### PR TITLE
RSECon 2024 highlights - internal presentation

### PR DESCRIPTION
**Pull request by jmarshrossney**
Quarto presentation with spaces left for colleagues to add their highlights from RSECon 2024.

Target audience is the EDS group. We could keep it very short and aim for the 30 minute weekly catch up, or schedule a dedicated meeting. Either way 5 minutes each is probably about all we want!

I'm planning to rattle through my slides quickly, with the intention of sharing the presentation afterwards in case people want to follow up on a link or something.

### CODE REVIEW

**Comment by metazool** [comment]
Thank you for taking the initative on this opportunity to reflect and share highlights! I think it's perfect material to suggest for one of the weekly half-hour EDS sessions (ideally in September, please)

**Comment by mattjbr123** [comment]
Added mine. I like this collaborative approach to presentation-making @jmarshrossney! Not used Quarto or GitHub for this type of thing before really

**Comment by jmarshrossney** [comment]
Should be as simple as changing the export format to powerpoint as instructed here: https://quarto.org/docs/presentations/powerpoint.html#powerpoint-templates

Although I'd much prefer to stick with revealjs and eventually [create a custom theme](https://quarto.org/docs/presentations/revealjs/themes.html)!

**Comment by jmarshrossney** [comment]
Just tested with the `UKCEH Powerpoint template.potx` template (found somewhere on sharepoint). Complete failure. Requires some work, probably creating a new template based on the original.

I'm happy to add a revealjs theme to my todo list, quite low down. I just can't with powerpoint.

**Comment by longr** [comment]
For a side project I need to create a reveal.js theme, could never quite get my head round it, but would be interested to work on one with you for CEH theme so I could learn.   Would be nice to create a latex/beamer one as well so pdf is an option.

**Review by metazool — APPROVED** [review]

**Pull request merged**
